name: Verilog Simulation

on:
  workflow_dispatch:

jobs:
  simulate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Icarus Verilog
      run: sudo apt-get update && sudo apt-get install -y iverilog

    - name: Compile and run testbench Multiplier
      run: |
        iverilog -g2012 -o simv RTL/Multiplier.v Testbenches/Multiplier_tb.sv
        vvp simv

    - name: Compile and run testbench Barrel_shifter
      run: |
        iverilog -g2012 -o simv RTL/Barrel_shifter.v Testbenches/Barrel_shifter_tb.sv
        vvp simv

    - name: Compile and run testbench ALU
      run: |
        iverilog -g2012 -o simv RTL/ALU.v Testbenches/ALU_tb.sv
        vvp simv
        
    - name: Compile and run testbench MAC
      run: |
        iverilog -g2012 -o simv RTL/MAC.v Testbenches/MAC_tb.sv
        vvp simv
        
    - name: Compile and run testbench Matrix multiplier
      run: |
        iverilog -g2012 -o simv RTL/Matrix_multiplier.v Testbenches/Matrix_multiplier_tb.sv
        vvp simv
